# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333f0b615fe261fca4cafb116612ceaa2e2f914602e1c1e8974b57790b87b3f96b03a288271ee9b14af15531f7bc44a661f4c1539ac698d4fef093265f8ba640
  

test:
  secret_key_base: 60cf771c25b171a933833485191fd0f447911ac72c8caa0fa6e4b9d407135684c7653489628bd0009b1e6cb047489567a41b9109c832f802df64c0c9106e3c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
